"""Pure domain logic: money, odds, legs, profit/loss. No Qt, no sqlite, no I/O.

The public surface is re-exported here so callers can ``from odds_pup.core import ...``.
"""

from odds_pup.core.checks import Advisory, AdvisoryCode, advisories_for
from odds_pup.core.commission import commission_fraction, format_commission, parse_commission
from odds_pup.core.errors import CoreError
from odds_pup.core.ladder import BETFAIR, LADDERS, Ladder
from odds_pup.core.model import (
    MAX_COMMISSION_BP,
    AuditKind,
    BetStatus,
    BetType,
    Leg,
    LegResult,
    Side,
    StakeKind,
    ValidationError,
    VenueKind,
)
from odds_pup.core.money import (
    MAX_MONEY_PENCE,
    MoneyError,
    Pence,
    format_pence,
    format_signed_pence,
    parse_money,
    pounds,
    to_pence,
)
from odds_pup.core.odds import (
    MAX_ODDS,
    OddsError,
    format_odds,
    parse_odds,
    storage_form,
    validate_odds,
)
from odds_pup.core.pl import (
    commission_by_venue,
    guaranteed_pl,
    leg_gross,
    open_liability,
    outcome_pl,
    pl_vector,
    realised_pl,
    status_of,
    validate_position,
)
from odds_pup.core.templates import (
    TWO_WAY_TYPES,
    TwoWayOutcome,
    TwoWayPosition,
    book_percentage,
    dutch_stakes,
    dutch_stakes_from_free_leg,
    exact_rating,
    optimal_lay_stake,
    rating,
    settle_two_way,
    two_way_position,
)

__all__ = [
    "BETFAIR",
    "LADDERS",
    "MAX_COMMISSION_BP",
    "MAX_MONEY_PENCE",
    "MAX_ODDS",
    "TWO_WAY_TYPES",
    "Advisory",
    "AdvisoryCode",
    "AuditKind",
    "BetStatus",
    "BetType",
    "CoreError",
    "Ladder",
    "Leg",
    "LegResult",
    "MoneyError",
    "OddsError",
    "Pence",
    "Side",
    "StakeKind",
    "TwoWayOutcome",
    "TwoWayPosition",
    "ValidationError",
    "VenueKind",
    "advisories_for",
    "book_percentage",
    "commission_by_venue",
    "commission_fraction",
    "dutch_stakes",
    "dutch_stakes_from_free_leg",
    "exact_rating",
    "format_commission",
    "format_odds",
    "format_pence",
    "format_signed_pence",
    "guaranteed_pl",
    "leg_gross",
    "open_liability",
    "optimal_lay_stake",
    "outcome_pl",
    "parse_commission",
    "parse_money",
    "parse_odds",
    "pl_vector",
    "pounds",
    "rating",
    "realised_pl",
    "settle_two_way",
    "status_of",
    "storage_form",
    "to_pence",
    "two_way_position",
    "validate_odds",
    "validate_position",
]
